README.md
* JS Unconf & Front End Design Conference
* small formatting fix
=> 2 new conferences added

README.md
- Naked.js
- Industry Conf
- JS Unconf
- O’Reilly Fluent Conference
=> Remove passed conferences

README.md
- Responsive Day Out 3
- Edge Conference
=> Add two upcoming conferences

README.md
Address issue [#14](https://github.com/frontendfront/front-end-conferences/issues/14).
=> Format European dates to standard

README.md
- UpFront Conferences
- UX London
- Front End Design Conferences
=> Remove old conferences

README.md
Even though it's happening fairly soon I thought it would be useful to have it on there.
=> added Hybrid conference

README.md
ref: https://twitter.com/CSSconfNO
=> Add CSSconf Nordic

README.md
ref: https://twitter.com/cssconfbudapest
=> Add CSSConf Budapest

README.md
Added upcoming Kharkov.js conference taking place in Kharkiv, Ukraine
=> Added Kharkiv.js to the list

README.md
Reverts frontendfront/front-end-conferences#73
=> Revert "Remove old conferences"

README.md
=> Added The Rolling Scopes conference

README.md
Hi there,
I've added FrontierConf into March 2016. I hope that's all ok.
Cheers,
John
=> Added FrontierConf

README.md
React.js Conf needs to be added to the USA list :)
=> Add React.js Conf USA

README.md
The conference is spread over 2 days.
=> Updated Frontend United date

README.md
FrontierConf has moved from 11 March to 16 November
=> Updated FrontierConf to 16 November

README.md
The first frontend conference in Osaka added to to the list.
=> Added Frontend Conference in Osaka

README.md
Seems like the line-breaks were wrong?
=> Broken line breaks

README.md
Add Front-Trends 2017 Conference
=> Add Front-Trends 2017

README.md
I'd like to propose to add the Agent Conference to the list of conferences. It's an unique combination of a conference and optional skiing event.
=> Add Agent Conference to conference list

README.md
A have added a new great event :)
=> Added Bulgaria Web Summit 2017

README.md
A one day JavaScript event in Linz, Austria :-) Would love to see you there!
=> adding Script'17 to the bunch

README.md
=> Fed/Jan17 - update to 2017 events

README.md
I added the enterJS conference next June in Germany.
=> Added enterJS conference

README.md
=> Added Universal JS Day

README.md
More info on the conference.
https://confoo.ca/
=> Added confoo conferences

README.md
The KFUG has another frontend conference this year 🎉
=> Added frontend conf in osaka, japan

README.md
https://activeingredients.info/
=> Adds a new conference: Active Indgredients

README.md
AngularUP - June 25th, 2017, Tel-Aviv
=> Add AngularUP

README.md
Adding CodeMash conference. CodeMash has session tracks and workshops for UX/UI/CSS, Javascript, Mobile, and more.
=> Adding CodeMash conference

README.md
=> added Source Up\! in South Africa

README.md
=> Add Form Function & Class 8

README.md
Added: 
[**You Gotta Love Frontend**](https://www.yougottalovefrontend.com/)  
30-31 October, 2017  
Tel Aviv, **Israel**
=> Added YGLF conf

README.md
=> Add FFConf

README.md
> FaaS (Function as a Service) architecture is radically changing how software is built how teams interface with each other and systems at scale. The old paradigms of REST are being replaced with remote functions, event-driven architectures, and new standards like GraphQL. We're organizing a space for Creativity, Exploration, Discussion and Learning to help developers learn and get in touch with the industry leaders on these topics.
>
> Join us for a full day event with speakers from industry leading FaaS comapnies and a panel discussion on the future of the FaaS tooling and infrastructure space!
=> Add Functions17 (Toronto)

README.md
=> Added Perfmatters Conf

README.md
=> Add Fronteers and KrakowJS

README.md
Adds the upcoming UtahJS conference to the list.
=> add UtahJS conf

README.md
and ordering the 2018 conferences
=> adding script'18

README.md
I have added another awesome event, 
Thanks!
=> Adding Bulgaria Web Summit 2018

README.md
I added this awesome conference in the list and I hope it helps. :)
=> Add Front in BH to South America's list

README.md
=> Add Web Standards Days Kiev 2017

README.md
added smashing conference in London
=> added smashing conference in London (7.2-8.2)

README.md
Hi,
it would be great if you could add our event to the public listing. Its the International JavaScript Conference.
Thanks,
Robert
=> Added International JavaScript Conference 2018

README.md
You Gotta Love Frontend 
Kyiv, 24-25 May 2018
=> Adding new conference

README.md
- React Finland
- ReactJS Day
- React Native EU
h/t Joana G
=> Add new conferences

README.md
[**ChernivtsiJS 2018**](https://chernivtsi.js.org)
P.S: And yeah, we really have this wonderful hall for conferencing :)
=> Add ChernivtsiJS

README.md
- 4th CSSConf of China here ：https://css.w3ctech.com/?l=en
03.31 / Xiamen,China
=> Add CSSConf China

README.md
Angular Conf Australia on 22nd June 2018
=> Added Angular Conf Australia

README.md
=> Added iJS Conf in Munich

README.md
=> Smashingconf Freiburg & NY

README.md
=> +ffconf 2018

README.md
Add an entry for FrontMania conference at 16 November in Utrecht, The Netherlands
=> Add FrontMania conference

README.md
=> New conference: ConFrontJS 2018

README.md
- remove conferences already taken place
- add new dates
- move Canada conference from Europe section to North America
=> Updated conferences

README.md
This PR adds the [**Covalence Electron Conference**](http://www.covalenceconf.com).
=> Add Covalence Conference

README.md
Hi there, I have added the SmashingConf for 2019. Thanks for setting up this list! Cheers, Charis @ Smashingconf
=> Added SmashingConfs for 2019

README.md
=> Add c't <webdev>

README.md
Conference with an exclusive focus on JavaScript frameworks: React, Angular, Vue
=> Added ComponentsConf

README.md
Hi! Thanks for maintaining this list! I added EmberConf 2019 now that registration has opened.
=> Add EmberConf 2019

README.md
Node.js is used every day by frontend developers and it's ecosystem plays a huge role.
=> Add NodeConf Colombia

README.md
Added CSS Day 13-14 June, Amsterdam (The Netherlands)
=> Add CSS Day 13-14 June, Amsterdam (The Netherlands)

README.md
Added Codemotion conferences ( Madrid, Milan and Berlin)
=> Added Codemotion conferences

README.md
Add upcoming jamstack conference in london
=> Add jamstack conf london

README.md
=> Add ember{{fest}}

README.md
New event in Feira de Santana, Brazil.
=> JSDay Feira de Santana 2019

README.md
Hello Hello,
I added ng-de to the list :)
Rob  <3
=> feat(conference): add ng-de conference 🎊

README.md
Hi, I added Full Stack Fest 2019 to the list!
=> Add Full Stack Fest 2019

README.md
=> Add HolyJS Moscow

README.md
a small frontend-focused conference in vienna, austria
=> add webclerks conference

README.md
=> Add Full Stack Europe

README.md
Workshops on Oct 24th
Main conference on Oct 25th
=> Add Script'19

README.md
=> Add You Gotta Love Frontend (YGLF) conference

README.md
=> CityJSConf 2020 addition 

README.md
* Add HalfStack 2020 events in Charlotte, Tel Aviv, NYC, Vienna, and London
* Clean up formatting of North America events to be more consistent
=> Add various HalfStack events

README.md
Hi
This PR adds scheduled yearly conferences organized by PassionatePeople (FrontendLove) in Amsterdam for 2020.
=> Add Scheduled NL Confs by Passionate People 2020

README.md
update webconf.asia status, remove trailing whitespace, formatting
=> Update webconf.asia status

README.md
=> Added Flashback Conference

README.md
Apologies. Just realized I screwed up and accidentally put the conference in Europe. I moved it to NA where it belongs.
=> Moved Flashback to North America

README.md
=> Add FrontFest 2020 Conference

README.md
And changed some hyphens to endashes :)
=> Added the 2020 date for Webconf.asia

README.md
=> Adds EmberConf 2020

README.md
Added Lead Dev Manager of Manager in London, June and Lead Dev San Francisco in October. Thank you!
=> Adding 2 events

README.md
Added React Native Eu conference in September (Poland).
=> Add react native eu conference

README.md
new conference in South America.
=> Add CausaConf to conferences

README.md
Updates to conferences postponed to later in the year due to covid-19.
=> covid-19 updates

README.md
* Add HalfStack Newquay
* Add HalfStack Phoenix 2021
* Add HalfStack Online
* Add other May online events
=> Add various online JS events

README.md
see update here https://webinale.de/de/
=> updated webinale date

README.md
There's been a change in the dates of these conferences so updating here to reflect the new date.
=> Update Conference Date

README.md
added Javascript Conference Munich
=> add Javascript Conference Munich

README.md
See new listing for 26-28 Oct in North America
=> Added An Event Apart Online Together: Fall Summit

README.md
Add BrazilJS.live that will happen live this weekend.
=> Add BrazilJS.live

README.md
=> added several conferences from Web Directions

README.md
Add React Miami Conference to North America events and remove past events that have ended.
=> Update conference list

README.md
Add App.js Conf to the list of conferences
=> Update README.md with App.js Conf 2022

README.md
=> Adding SmashingConf Freiburg and NY.

README.md
=> added angularday, reactjsday and vueday conf

README.md
Adding Wey Wey Web conference for UI lovers
=> Adding Wey Wey Web

README.md
Added info about App.js Conf 2023 🙂
=> Add App.js Conf 2023

README.md
Hello, please approve our changes. We added a new Javascript event in Munich for next year in March. Many Thanks
=> Added new JS Event

README.md
=> added 3 conferences

README.md
I am adding Wey Wey Web 23 conference.
=> Adding WWWeb23

README.md
would be great if we could display our conference here
=> added International JavaScript Conference Munich, 23-27 October 2023

README.md
Not affiliated with ffconf. I have just been to this one before and I think it's great
=> Added ffconf

README.md
This PR updates informations about the App.js 2024
=> Update info about App.js

README.md
Hi all! I've added the SmashingConfs for 2024! 
Have a great day!
=> New SmashingConfs for 2024

README.md
Hey, adding JSHeroes 2024 to the list, thanks!
=> add JSHeroes 2024

README.md
I am raising this PR to add [Middlesbrough Front End](https://middlesbroughfe.co.uk) Conference to the listings.
It looks like my VS Code auto-formatter has removed some whitespace from the file, hence the large additions count. But no other content has been modified. I assumed this would be okay, but please let me know if this is a cause for concern.
Thanks!
=> Add MFE2024 to listing

README.md
=> Add new Events

README.md
Hi, could you please add the new Changes. Thank you!
=> Add IJS Munich/London

README.md
Please merge the new International JavaScript Conference New York 2025. Thank you!
Husam
=> IJS New York

README.md
Hi all! Hope you're having a great day. We'd love to add our Freiburg and NYC conference to your website. 
Thanks so much! 
Cheers,
Charis
=> SmashingConf Freiburg and New York added.

README.md
Hey.
Added JSNation 2025 to the list of upcoming conferences.
Thanks.
=> Add JSNation 2025

README.md
Updated README.md to include Middlesbrough Front End Conference which takes place in June.
=> Add Middlesbrough Front End 2025

README.md
Hi, added JSNation US 2025 to the list of upcoming conferences.
Thanks in advance
=> Add JSNation US 2025

README.md
Hi,
It would be great if you could list our event on your repository.
The event is called "JavaScript & Angular Days" and takes place in october in Berlin.
Thanks in advance,
Robert
=> added JavaScript & Angular Days 20. - 24. October 2025 Berlin
